services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    container_name: pg_container
    ports:
      - '5432:5432'
    command: postgres -c max_connections=200
    volumes:
      - bookingdlite-nest-postgres:/var/lib/postgresql/data
  expo-dev:
    container_name: code_container
    image: io.ghcr.bookingdlite.starter
    build:
      context: .
      dockerfile: ./DockerFile
    env_file:
      - .env
    volumes:
      - code:/root/workspace
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vs-server:/root/.vscode-server
    links:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  vs-server: {}
  code: {}
  bookingdlite-nest-postgres: {}