# [Choice] Node.js version: 16, 14
# or others from https://hub.docker.com/_/node
FROM node:14.16.0-alpine3.13

# remove old yarn
RUN rm -rf /opt/yarn-v* /usr/local/bin/yarn /usr/local/bin/yarnpkg

# init for VS Code
RUN mkdir -p /root/workspace /root/.vscode-server 

# Install eslint typescript expo
RUN npm install -g eslint typescript expo-cli @expo/ngrok@^4.1.0

# Install jhipster nodejs
RUN npm install -g generator-jhipster-nodejs

#Install git
RUN apk update && apk add git

RUN apk add openssh-client

CMD /bin/sh -c "while sleep 86000; do :; done"